### PR TITLE
Pull request for ghc-7.10.2

### PR DESCRIPTION
**Pull request by travisbot**
Resolves travis-ci/travis-ci#4478.

***NOTE***

There are setuid/seteuid/setgid bits found. Be sure to check the check build result.

Add packages: ghc-7.10.2 ghc-7.10.2-prof ghc-7.10.2-dyn ghc-7.10.2-htmldocs

See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/73902738.

### CODE REVIEW

**Comment by hvr** [comment]
Well, those setuid strings found are there because GHC contains FFI bindings allowing Haskell programs to perform setuid operations... nothing suprising here...

**Comment by ekmett** [comment]
I'm starting to regret moving to the containerized infrastructure. =/

This is currently requiring me to disable all the actual test suite builds in the testing for almost all of my packages, because while I get a version of cabal it isn't the one that ships with `7.10.1`, and the `7.10.2` build is held up on this.

**Comment by kolmodin** [comment]
I would very much like to see this resolved.

**Comment by kolmodin** [comment]
@BanzaiMan could you please have a look?
GHC is a compiler and it ships with a library for programs to use setuid/setgid. Other compilers/interpreters who also ship libraries like this one have been white listed.

Thanks!

**Comment by svenpanne** [comment]
Just another "me too" to raise the attention to this issue a bit more. `7.10.2` is the latest official release of GHC and contains a few crucial fixes which `7.10.1` doesn't have.

As mentioned above, the automated check returned bogus results: Of course GHC's libraries contain binding to `setuid` and friends, but that's not different from e.g. Python having `os.setuid`. How is this handled for other languages and their related libraries?

**Comment by BanzaiMan** [comment]
Sorry for the delay, everyone.

**Comment by hvr** [comment]
Thanks!

**Comment by ekmett** [comment]
Woohoo!

**Comment by kolmodin** [comment]
Thanks!

**Pull request merged**
