### PR TITLE
Pull request for mpg123

### PR DESCRIPTION
**Pull request by travisbot**
Resolves travis-ci/apt-package-whitelist#1941.

**_NOTE**_

setuid/seteuid/setgid bits were found. Be sure to check the build result.

Add packages: mpg123 libmpg123-0 libmpg123-dev

See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/94753753.

### CODE REVIEW

**Comment by dsvensson** [comment]
So what happens now?

**Comment by mpbraendli** [comment]
Hello, I also need libmpg123-dev for dablin maintained by @basicmaster

https://travis-ci.org/Opendigitalradio/dablin

Best regards,
mpb

**Comment by BanzaiMan** [comment]
If you need this package now, I advise you to use the new GCE infrastructure. You don't have access to caching, but you have `sudo`.

**Comment by mpbraendli** [comment]
What is GCE ? I'm afraid I was unable to find any information on docs.travis-ci.com nor with a websearch. 

https://docs.travis-ci.com/user/ci-environment/ shows four different environments, which one is it ?

**Comment by BanzaiMan** [comment]
@mpbraendli Sorry about the confusion there. The document you point to needs to be updated. In the meantime, see https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future. `sudo: required` should get you there.

**Comment by mpbraendli** [comment]
I suppose I'm using GCE then, since I have both

    sudo: required
    dist: trusty

It still says "disallowing packages: libmpg123-dev" in my job
https://travis-ci.org/Opendigitalradio/dablin/jobs/97682741

The handling of the packages vs GCE/non-GCE is not so clear to me. Do I have to wait for libmpg123-dev to be accepted in the whitelist ?

This is what I'm using:
https://github.com/Opendigitalradio/dablin/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
@mpbraendli I meant to use `sudo apt-get install …` ***instead of*** the APT addon.

**Comment by mpbraendli** [comment]
Ok I'll try that. Thanks!

**Pull request merged**
