### PR TITLE
Pull request for jq

### PR DESCRIPTION
**Pull request by travisbot**
Resolves travis-ci/apt-package-whitelist#1394.
Add packages: jq

See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/86171196.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
`jq` is pre-installed.

**Comment by oncletom** [comment]
Is there a way to get a newer version of jq though? Like `jq@1.5`? Or shall I request this specific version to be whitelisted? Thanks a lot @BanzaiMan :-)

**Comment by BanzaiMan** [comment]
If you want a newer version right now, it is best to just grab a binary.

The next build env update (sorry, no ETA) will include 1.5 or later via cookbooks: https://github.com/travis-ci/travis-cookbooks/tree/master/cookbooks/jq.

**Comment by oncletom** [comment]
Perfect :-) that's what I ended doing, using the binary. Thanks a lot!

**Pull request closed without merging**
