### PR TITLE
Pull request for jackd1

### PR DESCRIPTION
**Pull request by travisbot**
Resolves travis-ci/apt-package-whitelist#1127.

***NOTE***

setuid/seteuid/setgid bits were found. Be sure to check the build result.

Add packages: jackd1 libjack0 jackd1-firewire libjack-dev

See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/78952891.

### CODE REVIEW

**Comment by umlaeute** [comment]
i was just to submit another white-list request for `libjack-dev` when i found #1127 .

Does the quick closing of this PR mean that the package is *not* considered for inclusion?

because checking the [build-logs](http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/78952891) shows, that the failure was triggered by mentioning `setuid` in a changelog entry from 2004 (that's 13 years ago).

back then `setuid` was used to grant realtime priviliges to low-latency sound applications;
this has changed since then (around 2009) by using pam-limits.

afaikt, the package itself doesn't use setuid at all, so i still think it ought to be included in the whitelist.

**Comment by mickflemm** [comment]
libjack-dev should be just the libs but for some reason ubuntu/debian ships both the libs and the binaries under that. There is no need for the suid bit (it's not there anymore anyway), I don't think anyone will run jackd as part of the build process but not having the libraries and the headers there breaks things. Please whitelist this one...

**Comment by umlaeute** [comment]
@mickflemm this is definitely wrong.

the `libjack-dev? package *only* provides headers, documentation and a static library to link against.
the problem seems to be that travis checks the source package (`jack-audio-connection-kit`) from which `libjack-dev` is built: this source package also builds other packages, e.g. `libjack` and `jackd` - the latter potentially requiring real-time priviliges.
now the test that travis is running is basically an `rgrep setuid .` - which returns a result, as a changelog entry from 2004 mentioned *setuid* being used for starting jackd.

there is *nothing* requiring `setuid` in the current `libjack-dev` package (and in any other binary package built from `jack-audio-connection-kit`)

**Comment by umlaeute** [comment]
therefore I would be interested, why @BanzaiMan closed this.

**Pull request closed without merging**
