### PR TITLE
Add some packages from ubuntu-precise to ubuntu-trusty

### PR DESCRIPTION
**Pull request by aquileia**
As we (www.github.com/wesnoth/wesnoth) will apply for the Ubuntu Trusty beta programme of travis, a few packages would need to be added to the `ubuntu-trusty` whitelist. All of these are already available in `ubuntu-precise`, so this shouldn't require manual validation.

I will also create a separate PR for version 2 of the SDL libraries which we plan to use in the future. As these aren't part of the `ubuntu-precise` whitelist yet, that PR will probably have to be checked manually. I kept that commit separate so that this PR won't be delayed due to it.

Added development libraries:
- boost
- cairo
- fribidi
- pango
- SDL 1.2

Added tools:
- gdb
- moreutils

### CODE REVIEW

**Comment by BanzaiMan** [comment]
On our current Trusty images, you can use `sudo`, so you shouldn't need the APT addon.

**Comment by aquileia** [comment]
Shouldn't need or shouldn't use? We'd prefer to use the future-proof container based builds, especially as the speed-up seems to be noticeable for our repo.

**Comment by BanzaiMan** [comment]
"Should *not*". http://docs.travis-ci.com/user/docker/

**Comment by aquileia** [comment]
I might have found a bug: My test build
https://travis-ci.org/aquileia/wesnoth/builds/77779224
uses a trusty worker, but the `ubuntu-precise` whitelist.

**Comment by meatballhat** [comment]
Resolved elsewhere.  Please yell if you see otherwise ❤️

**Pull request closed without merging**
