### PR TITLE
Add hunspell packages

### PR DESCRIPTION
**Pull request by dhensby**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello. Thank you for taking time to open a PR.

We are in the process of automating package request process. A part of it is running tests automatically. As this PR does not come with tests, we are not able to accept it.

Thank you for your understanding.

**Comment by dhensby** [comment]
Thanks @BanzaiMan - I take it there's nothing I can do to expedite the process. Do you have any timeframe for when the automated package request process will be up and running?

**Comment by BanzaiMan** [comment]
@dhensby We are working on expediting the process. (This PR is of particular interest, since it adds so many. I want to make sure that we don't have to process every single one of them separately; so I may end up tweaking and testing the process on this PR, and this may get done faster)

**Comment by dhensby** [comment]
Lucky me!

Ok, well thank you for letting me know - we'll stay on the legacy infrastructure for the projects that need this until we can move.

Thanks!

**Comment by BanzaiMan** [comment]
@dhensby Looks like https://github.com/travis-ci/apt-package-whitelist/pull/48 missed all the localization packages. (Meaning, they do not come from the same source package as `hunspell`.) Do you know where you found them?

**Comment by dhensby** [comment]
I did:

`apt-cache search hunspell`

I just need the en-us one, but thought I'd add all of them for thoroughness

**Comment by BanzaiMan** [comment]
I see. I'll leave that up to you whether or not you'd like to get other localizations, then.

**Comment by dhensby** [comment]
Looks like #48 didn't pull any in. What would I need to do to get the others in?

**Comment by BanzaiMan** [comment]
@dhensby Looks like each localizations are separate packages. http://packages.ubuntu.com/precise/all/hunspell-ar, http://packages.ubuntu.com/precise/all/hunspell-en-us and so on.

**Comment by dhensby** [comment]
Oh good fun! Can I get the en-us one it, please?

**Comment by BanzaiMan** [comment]
@dhensby Could you open a new issue, please?

**Comment by dhensby** [comment]
@BanzaiMan please see #99

**Pull request closed without merging**
