### PR TITLE
Replace libxcb-ewmh-dev with libxcb-ewmh1-dev

### LINKED ISSUE #1581: APT whitelist request for libxcb-ewmh1-dev

### PR DESCRIPTION
**Pull request by HarveyHunt**
The incorect package was added to the whitelist in 63554b0cf -
libxcb-ewmh-dev only exists in versions after Ubuntu Precise.
Precise uses libxcb-ewmh1-dev, so update the whitelist accordingly.

Fixes #1581

### CODE REVIEW

**Comment by HarveyHunt** [comment]
Ping @BanzaiMan

**Comment by HarveyHunt** [comment]
@BanzaiMan Any hope of this being merged?

**Comment by HarveyHunt** [comment]
Ping @BanzaiMan @meatballhat

**Comment by sardemff7** [comment]
Now Trusty builds using `libxcb-ewmh-dev` are broken. Can’t we just have both?

**Pull request merged**
