### PR TITLE
Whitelisted the MongoDB packages for 2.6 and above

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hello. Thank you for taking time to open a PR.

We are in the process of automating package request process. A part of it is running tests automatically. As this PR does not come with tests, we are not able to accept it.

Thank you for your understanding.

**Comment by thedrow** [comment]
I have no idea where the tests are. I guess I'll have to wait.

**Comment by BanzaiMan** [comment]
@thedrow PPA from mongodb.org is source whitelisted, so we should be able to handle them. The automation process expects to find the issue title precisely the way it is described in README. Here, you'd want `APT whitelist request for mongodb-org`, I believe, assuming that the source package defines `-server` and `-mongos`. I am not quite sure about the `i386` variant.

**Comment by thedrow** [comment]
I checked it does contain all of those variants.
There are two PPAs. One for Mongo 2.x and the other for Mongo 3.x. We need both.

**Pull request closed without merging**
