### PR TITLE
Pull request for qemu

### PR DESCRIPTION
**Pull request by travisbot**
***NOTE***

There are setuid/seteuid/setgid bits found. Be sure to check the check build result.

Resolves travis-ci/apt-package-whitelist#483.
Add packages: qemu qemu-system qemu-block-extra qemu-system-common qemu-system-misc qemu-system-arm qemu-system-mips qemu-system-ppc qemu-system-sparc qemu-system-x86 qemu-user qemu-user-static qemu-user-binfmt qemu-utils qemu-guest-agent qemu-kvm libcacard0 libcacard-dev libcacard-tools

See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/73195921.

### CODE REVIEW

**Comment by klange** [comment]
I'm wondering what the status of this pull request is. Are we stuck waiting on verification that the `setuid` references are benign? Is there anything I or the other requesters could do to speed things along?

**Comment by Shamar** [comment]
@BanzaiMan I support the @klange's question: every project that uses Travis-CI to build a operative system needs qemu to run tests.

As an alternative, we should be able to temporarily downgrade to the previous infrastructure while waiting for qemu in the new one.

**Comment by duckinator** [comment]
Also interested in the status of this, and if there's any way I can help move things along.

**Comment by simi** [comment]
I'm also interested here.

**Pull request merged**
